// <auto-generated />
using System;
using Hospital_Web_Project_Fall.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospital_Web_Project_Fall.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231229221225_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Hospital_Web_Project_Fall.Models.Domain.Doktor", b =>
                {
                    b.Property<Guid>("DoktorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DoktorAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoktorBrans")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoktorMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoktorSifre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoktorSoyadi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoktorTelefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoktorUnvan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DoktorId");

                    b.ToTable("Doktor");
                });
#pragma warning restore 612, 618
        }
    }
}
